package com.zte.smart.community.bean;

import java.math.BigDecimal;
import java.util.Date;

public class SmartCommunityPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.ID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.TYPE
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.SOURCE
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private Short source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.USER_ID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.PHONE_RECORD_ID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private String phoneRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.TITLE
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.CONTENT
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.STATUS
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.CREATE_TIME
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.LAST_UPDATE_UID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private BigDecimal lastUpdateUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.LAST_UPDATE_TIME
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZTE_SMART_COMMUNITY_POST.EVALUATION
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    private Short evaluation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.ID
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.ID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.ID
     *
     * @param id the value for ZTE_SMART_COMMUNITY_POST.ID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.TYPE
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.TYPE
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.TYPE
     *
     * @param type the value for ZTE_SMART_COMMUNITY_POST.TYPE
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.SOURCE
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.SOURCE
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public Short getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.SOURCE
     *
     * @param source the value for ZTE_SMART_COMMUNITY_POST.SOURCE
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setSource(Short source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.USER_ID
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.USER_ID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.USER_ID
     *
     * @param userId the value for ZTE_SMART_COMMUNITY_POST.USER_ID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.PHONE_RECORD_ID
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.PHONE_RECORD_ID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public String getPhoneRecordId() {
        return phoneRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.PHONE_RECORD_ID
     *
     * @param phoneRecordId the value for ZTE_SMART_COMMUNITY_POST.PHONE_RECORD_ID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setPhoneRecordId(String phoneRecordId) {
        this.phoneRecordId = phoneRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.TITLE
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.TITLE
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.TITLE
     *
     * @param title the value for ZTE_SMART_COMMUNITY_POST.TITLE
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.CONTENT
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.CONTENT
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.CONTENT
     *
     * @param content the value for ZTE_SMART_COMMUNITY_POST.CONTENT
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.STATUS
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.STATUS
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.STATUS
     *
     * @param status the value for ZTE_SMART_COMMUNITY_POST.STATUS
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.CREATE_TIME
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.CREATE_TIME
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.CREATE_TIME
     *
     * @param createTime the value for ZTE_SMART_COMMUNITY_POST.CREATE_TIME
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.LAST_UPDATE_UID
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.LAST_UPDATE_UID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public BigDecimal getLastUpdateUid() {
        return lastUpdateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.LAST_UPDATE_UID
     *
     * @param lastUpdateUid the value for ZTE_SMART_COMMUNITY_POST.LAST_UPDATE_UID
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setLastUpdateUid(BigDecimal lastUpdateUid) {
        this.lastUpdateUid = lastUpdateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.LAST_UPDATE_TIME
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.LAST_UPDATE_TIME
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for ZTE_SMART_COMMUNITY_POST.LAST_UPDATE_TIME
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZTE_SMART_COMMUNITY_POST.EVALUATION
     *
     * @return the value of ZTE_SMART_COMMUNITY_POST.EVALUATION
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public Short getEvaluation() {
        return evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZTE_SMART_COMMUNITY_POST.EVALUATION
     *
     * @param evaluation the value for ZTE_SMART_COMMUNITY_POST.EVALUATION
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    public void setEvaluation(Short evaluation) {
        this.evaluation = evaluation;
    }
}