package com.zte.smart.community.mapper;

import com.zte.smart.community.bean.SmartCommunityPost;
import com.zte.smart.community.bean.SmartCommunityPostExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmartCommunityPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    int countByExample(SmartCommunityPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    int deleteByExample(SmartCommunityPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    int insert(SmartCommunityPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    int insertSelective(SmartCommunityPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    List<SmartCommunityPost> selectByExample(SmartCommunityPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    SmartCommunityPost selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:26 CST 2014
     */
    int updateByExampleSelective(@Param("record") SmartCommunityPost record, @Param("example") SmartCommunityPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:27 CST 2014
     */
    int updateByExample(@Param("record") SmartCommunityPost record, @Param("example") SmartCommunityPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:27 CST 2014
     */
    int updateByPrimaryKeySelective(SmartCommunityPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZTE_SMART_COMMUNITY_POST
     *
     * @mbggenerated Thu May 29 19:19:27 CST 2014
     */
    int updateByPrimaryKey(SmartCommunityPost record);
}